apiVersion: v1
kind: Pod
metadata:
  name: high-cpu-pod
spec:
  containers:
  - name: mycontainer
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while :; do echo 'Consuming CPU'; done"]

    resources:
      limits:
        memory: "100Mi"
        cpu: "200m" # Consuma 200 milicores (CPU milicores)
